config/routes.rb
Rails.application.routes.draw do
  resources :ads
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "ads#index"
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  has_one_attached :image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]

  # GET /ads or /ads.json
  def index
    @ads = Ad.paginate(page: params[:page],per_page: 4)
  end
  # GET /ads/1 or /ads/1.json
  def show
    @ad = Ad.find_by(id: params[:id])
    @user = @ad.user
  end
  # GET /ads/new
  def new
    @ad = current_user.ads.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if (@ad= current_user.ads.create(ad_params))
        format.html { redirect_to @ad, notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:title, :description, :price, :catorgory, :image, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <style>
      body {
          margin: 0;
          padding: 0;
          font-family: sans-serif;
          background: linear-gradient(to right, #b92b27, #1565c0)
      }

      .card {
          margin-bottom: 20px;
          border: none
      }

      .box {
          width: 500px;
          padding: 40px;
          position: absolute;
          left: 50%;
          background-color: #191919 !important;

      ;
          text-align: center;
          transition: 0.25s;
          margin-top: 100px
      }
      .box input[type="text"],
      .box input[type="email"],
      .box input[type="password"] {
          border: 0;
          background: none;
          display: block;
          margin: 20px auto;
          text-align: center;
          border: 2px solid #3498db;
          padding: 10px 10px;
          width: 250px;
          outline: none;
          color: white;
          border-radius: 24px;
          transition: 0.25s
      }

      .box h1 {
          color: white;
          text-transform: uppercase;
          font-weight: 500
      }
      .box input[type="text"]:focus,
      .box input[type="email"]:focus,
      .box input[type="password"]:focus {
          width: 300px;
          border-color: #2ecc71
      }

      .box input[type="submit"] {
          border: 0;
          background: none;
          display: block;
          margin: 20px auto;
          text-align: center;
          border: 2px solid #2ecc71;
          padding: 14px 40px;
          outline: none;
          color: white;
          border-radius: 24px;
          transition: 0.25s;
          cursor: pointer
      }

      .box input[type="submit"]:hover {
          background: #2ecc71
      }

      .forgot {
          text-decoration: underline
      }

      ul.social-network {
          list-style: none;
          display: inline;
          margin-left: 0 !important;
          padding: 0
      }

      ul.social-network li {
          display: inline;
          margin: 0 5px
      }

      .social-network a.icoFacebook:hover {
          background-color: #3B5998
      }

      .social-network a.icoTwitter:hover {
          background-color: #33ccff
      }

      .social-network a.icoGoogle:hover {
          background-color: #BD3518
      }

      .social-network a.icoFacebook:hover i,
      .social-network a.icoTwitter:hover i,
      .social-network a.icoGoogle:hover i {
          color: #fff
      }

      a.socialIcon:hover,
      .socialHoverClass {
          color: #44BCDD
      }

      .social-circle li a {
          display: inline-block;
          position: relative;
          margin: 0 auto 0 auto;
          border-radius: 50%;
          text-align: center;
          width: 50px;
          height: 50px;
          font-size: 20px
      }

      .social-circle li i {
          margin: 0;
          line-height: 50px;
          text-align: center
      }

      .social-circle li a:hover i,
      .triggeredHover {
          transform: rotate(360deg);
          transition: all 0.2s
      }

      .social-circle i {
          color: #fff;
          transition: all 0.8s;
          transition: all 0.8s
      }
  </style>






</head>
<body>

<div style="margin-top: -50px" class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card box">

        <%= form_with(model: ad) do |f| %>
          <% if ad.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

              <ul>
                <% ad.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <h1>Create New Ad</h1>
          <%= f.text_field :title, placeholder:"Enter title"%>
          <%= f.file_field :image%>
          <%= f.text_field :description, placeholder:"Description"%>
          <%= f.text_field :price, placeholder:"Enter price"%>
          <%= f.text_field :catorgory, placeholder:"Enter category"%>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

<%#= form_with(model: ad) do |form| %>
  <%# if ad.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>-->

<!--      <ul>-->
        <%# ad.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div class="field">-->
    <%#= form.label :title %>
    <%#= form.text_field :title %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :image %>
    <%#= form.file_field :image %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label :description %>
    <%#= form.text_field :description %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label :price %>
    <%#= form.text_field :price %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :catorgory %>
    <%#= form.text_field :catorgory %>
<!--  </div>-->

<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
  </style>
</head>
<body>



<img style="width: 100%;height: 200px" src="olx.jpg">

<h1 style="text-align: center">Ads</h1>
<table>

<tbody>

<div style="width: 100%; height: 250px; padding-left: 170px">

<% @ads.each do |ad| %>
    <div style="height: 280px;  float: left; width: 300px;margin-left: 10px ;margin-top: 10px; border: 1px solid">
      <div>
        <% if ad.image.attached? %>
          <%=image_tag(ad.image,  size: "298x200") %>
        <% end %>
      </div>
    <p style="margin-top: 10px"> <strong>Title : </strong><%= ad.title %></p>

    <strong> Price:     </strong><%= ad.price %> $

    <%#= ad.description %>
    <%#= ad.catorgory %>
      <div style="margin-top: -50px; padding-left: 200px">
    <%= link_to 'Show', ad,class: 'btn btn-success' %>
      </div>
    <%#= link_to 'Edit', edit_ad_path(ad) %>
    <%#= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %>

    </div>

<% end %>
  <div style="padding-top: 300px">
  <%= will_paginate @ads ,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

</tbody>
</table>

<br>
</body>
</html>

app/views/ads/new.html.erb
<%= render 'form', ad: @ad %>

app/views/ads/show.html.erb
<div style="text-align: center; background-color: #e9ecef; width: 50%; margin-left: 20%">

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>
<div >
  <% if @ad.image.attached? %>
    <%=image_tag(@ad.image,  size: "200x200") %>
  <% end %>
</div>
<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>
<p>
  <strong>Poster Name:</strong>
  <%= @user.email %>

</p>
<p>
  <strong>Price:</strong>
  <%= @ad.price %>
</p>

<p>
  <strong>Catorgory:</strong>
  <%= @ad.catorgory %>
</p>
<% if user_signed_in? %>
<% if current_user.id == @user.id %>

<%= link_to 'Edit', edit_ad_path(@ad),class: 'btn btn-success' %> |
    <%= link_to 'Back', ads_path,class: 'btn btn-success' %>
  <%else %>
<%= link_to 'Back', ads_path,class: 'btn btn-success' %>
  <%end %>
<%end %>

</div>

app/views/home/home.html.erb
<p>Hello W</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
  <%= render 'shared/navbar' %>
  <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'OLX', ads_path(current_user),class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
          <%= link_to 'Home ', ads_path(current_user),class: "nav-link"%>
        </li>
        <%if user_signed_in? %>
          <li style="padding-left: 1200px" class="nav-item">
            <%= link_to 'Sign Out ', destroy_user_session_path, method: :delete,class: "nav-link"%>
          </li>
          <%= link_to 'Create Ad ', new_ad_path,class: "nav-link"%>
         <%else %>
        <li style="padding-left: 1200px" class="nav-item">
          <%= link_to 'Sign In ', new_user_session_path,class:"nav-link" %>
        </li>
        <li style="padding-left: 5px" class="nav-item">
          <%= link_to 'Register', new_user_registration_path ,class: "nav-link"%>
        </li>
        <%end %>
      </ul>

    </div>
  </div>
</nav>